# Generated by Django 5.2.2 on 2025-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Email подтверждён"),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Токен верификации"
            ),
        ),
    ]
