# Generated by Django 5.2.2 on 2025-07-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_verified_user_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_token_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания токена"
            ),
        ),
    ]
