# Generated by Django 5.2.2 on 2025-07-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_verification_token_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["full_name"],
                "permissions": [
                    ("can_view_users", "Может просматривать список пользователей"),
                    ("can_block_user", "Может блокировать пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
