# Generated by Django 5.2.2 on 2025-06-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["full_name"],
            },
        ),
    ]
