# Generated by Django 5.2.2 on 2025-07-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "permissions": [
                    ("can_view_all_clients", "Может просматривать всех клиентов")
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_disable_mailing", "Может отключать рассылки"),
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_block_users", "Может блокировать пользователей"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
